// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5Dje2LiyaL4Cxd1G0Nyej-TbxG66pPZ8',
    appId: '1:392958934838:web:6d2427c868a0b134d3fd97',
    messagingSenderId: '392958934838',
    projectId: 'queue-management-b462e',
    authDomain: 'queue-management-b462e.firebaseapp.com',
    storageBucket: 'queue-management-b462e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK1eYb8tad2S5tOThwTusbkU6Z4edKBMs',
    appId: '1:392958934838:android:479c5e5da3318574d3fd97',
    messagingSenderId: '392958934838',
    projectId: 'queue-management-b462e',
    storageBucket: 'queue-management-b462e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo18ETyUlEJ6zi7Gt6K0RiX0q9CJihcKM',
    appId: '1:392958934838:ios:48a1cc838b9276e4d3fd97',
    messagingSenderId: '392958934838',
    projectId: 'queue-management-b462e',
    storageBucket: 'queue-management-b462e.appspot.com',
    iosClientId: '392958934838-4m5h3slthb1t8uk15im5bi1mu8as9lgi.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFirebase',
  );
}
